apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor-metrics-exporter
  labels:
    release: prometheus
    app: prometheus
spec:
  jobLabel: job
  selector:
    matchLabels:
      job: node-metrics-exporter
      app: service-metrics-exporter
  endpoints:
  - port: web
    path: /metrics
    interval: 1s
    scrapeTimeout: 1s
    tlsConfig:
      insecureSkipVerify: true