apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy-gateway
  name: deploy-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-gateway
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-gateway
    spec:
      containers:
      - image: miketzan/gateway:latest
        name: gateway
        imagePullPolicy: Always
        resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: service-gateway
  labels:
    job: node-gateway
    app: service-gateway
spec:
  type: NodePort
  selector:
    app: deploy-gateway
  ports:
    - name: web
      protocol: TCP
      port: 7000
      targetPort: 7000
      nodePort: 30006