apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor-warehouseapi
  labels:
    release: prometheus
    app: prometheus
spec:
  jobLabel: job
  selector:
    matchLabels:
      app: service-warehouseapi
  endpoints:
  - port: web
    path: /metrics
    interval: 30s
